GET http://localhost:8000/health

###

POST http://localhost:8000
Content-Type: application/json

{
  "name": "Mushfiq",
  "country": "BD",
  "level": 1
}

###

GET http://localhost:8000

###

GET http://localhost:8000/Fx1VicbX

###

PATCH http://localhost:8000/Fx1VicbX5
Content-Type: application/json

{
  "name": "Mushfiqur Rahman",
  "level": 5
}

###

PUT http://localhost:8000/Fx1VicbX
Content-Type: application/json

{
  "name": "Chota Vim"
}


###

DELETE  http://localhost:8000/o0v8Zwb